apiVersion: v1
kind: Service
metadata:
  name: docs
  namespace: docs
spec:
  type: ClusterIP
  selector:
    app: docs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
  namespace: docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs
  template:
    metadata:
      labels:
        app: docs
    spec:
      containers:
        - name: docs
          image: "docs:1.0.1"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
